"""add_written_question_fields

Revision ID: aed4c64a6bdb
Revises: 0d2562c05b38
Create Date: 2026-03-15 17:29:43.529678

"""
from alembic import op
import sqlalchemy as sa


revision = 'aed4c64a6bdb'
down_revision = '0d2562c05b38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_type', sa.String(length=20), nullable=True))
    op.add_column('questions', sa.Column('written_parts', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('keywords_1', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('keywords_2', sa.Text(), nullable=True))
    op.alter_column('questions', 'option_a',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'option_b',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'option_c',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'option_d',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('questions', 'option_d',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'option_c',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'option_b',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'option_a',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('questions', 'keywords_2')
    op.drop_column('questions', 'keywords_1')
    op.drop_column('questions', 'written_parts')
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###